-- MySQL Script generated by MySQL Workbench
-- Thu Jan 23 19:23:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OnlineStore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `OnlineStore` ;

-- -----------------------------------------------------
-- Schema OnlineStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnlineStore` DEFAULT CHARACTER SET utf8 ;
USE `OnlineStore` ;

-- -----------------------------------------------------
-- Table `OnlineStore`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`Product` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`Product` (
  `product_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(20,2) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`Category` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`Category` (
  `category_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `parent_category` BIGINT(20) NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC) VISIBLE,
  INDEX `fk_category_category1_idx` (`parent_category` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`parent_category`)
    REFERENCES `OnlineStore`.`Category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`User` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`User` (
  `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `password_hash` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`Order_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`Order_status` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`Order_status` (
  `order_status_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`order_status_id`),
  UNIQUE INDEX `status_name_UNIQUE` (`status_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`Order` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`Order` (
  `order_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `discount` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `order_status_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`order_id`, `order_status_id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_order_order_status1_idx` (`order_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `OnlineStore`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_order_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `OnlineStore`.`Order_status` (`order_status_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`Role` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`Role` (
  `role_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`Product_review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`Product_review` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`Product_review` (
  `review_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `rating` DECIMAL(2,1) NULL,
  `created_at` DATETIME NOT NULL,
  `product_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_product_review_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_product_review_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_review_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `OnlineStore`.`Product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_review_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `OnlineStore`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`Order_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`Order_product` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`Order_product` (
  `order_product_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `price_at_order` FLOAT NOT NULL,
  `quantity` SMALLINT(5) NOT NULL,
  `order_id` BIGINT(20) NOT NULL,
  `product_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`order_product_id`),
  INDEX `fk_order_item_order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_item_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_item_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `OnlineStore`.`Order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_item_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `OnlineStore`.`Product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`Product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`Product_category` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`Product_category` (
  `category_id` BIGINT(20) NOT NULL,
  `product_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`category_id`, `product_id`),
  INDEX `fk_product_category_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `OnlineStore`.`Category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_category_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `OnlineStore`.`Product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`Address` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`Address` (
  `adress_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `zip_code` VARCHAR(45) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`adress_id`),
  INDEX `fk_adress_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_adress_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `OnlineStore`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`Payment_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`Payment_method` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`Payment_method` (
  `payment_method_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`payment_method_id`),
  UNIQUE INDEX `status_name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`Payment` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`Payment` (
  `payment_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `payment_method_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `order_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`payment_id`, `payment_method_id`),
  INDEX `fk_payment_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_payment_payment_method1_idx` (`payment_method_id` ASC) VISIBLE,
  INDEX `fk_payment_order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `OnlineStore`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_payment_method1`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `OnlineStore`.`Payment_method` (`payment_method_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `OnlineStore`.`Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`User_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`User_role` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`User_role` (
  `user_id` BIGINT(20) NOT NULL,
  `role_id` BIGINT(20) NOT NULL,
  INDEX `fk_user_role_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_role_role1_idx` (`role_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `role_id`),
  CONSTRAINT `fk_user_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `OnlineStore`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `OnlineStore`.`Role` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`Shipping_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`Shipping_status` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`Shipping_status` (
  `shipping_status_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`shipping_status_id`),
  UNIQUE INDEX `status_name_UNIQUE` (`status_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`Carrier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`Carrier` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`Carrier` (
  `carrier_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `contact_number` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NULL,
  `website` VARCHAR(250) NULL,
  PRIMARY KEY (`carrier_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`Shipping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`Shipping` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`Shipping` (
  `shipping_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `shipping_carrier` VARCHAR(45) NOT NULL,
  `tracking_number` VARCHAR(45) NOT NULL,
  `shipped_at` DATETIME NOT NULL,
  `estimated_delivery` DATE NULL,
  `shipping_status_id` BIGINT(20) NOT NULL,
  `order_id` BIGINT(20) NOT NULL,
  `adress_id` BIGINT(20) NOT NULL,
  `carrier_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`shipping_id`, `shipping_status_id`),
  INDEX `fk_shipping_shipping_status1_idx` (`shipping_status_id` ASC) VISIBLE,
  UNIQUE INDEX `shipping_carrier_UNIQUE` (`shipping_carrier` ASC) VISIBLE,
  UNIQUE INDEX `tracking_number_UNIQUE` (`tracking_number` ASC) VISIBLE,
  INDEX `fk_Shipping_Order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_Shipping_Address1_idx` (`adress_id` ASC) VISIBLE,
  INDEX `fk_Shipping_Carrier1_idx` (`carrier_id` ASC) VISIBLE,
  CONSTRAINT `fk_shipping_shipping_status1`
    FOREIGN KEY (`shipping_status_id`)
    REFERENCES `OnlineStore`.`Shipping_status` (`shipping_status_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Shipping_Order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `OnlineStore`.`Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shipping_Address1`
    FOREIGN KEY (`adress_id`)
    REFERENCES `OnlineStore`.`Address` (`adress_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shipping_Carrier1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `OnlineStore`.`Carrier` (`carrier_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
