-- MySQL Script generated by MySQL Workbench
-- Thu Jan 16 14:33:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OnlineStore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `OnlineStore` ;

-- -----------------------------------------------------
-- Schema OnlineStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnlineStore` DEFAULT CHARACTER SET utf8 ;
USE `OnlineStore` ;

-- -----------------------------------------------------
-- Table `OnlineStore`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`product` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`product` (
  `product_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(20,2) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`category` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`category` (
  `category_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `parent_category` BIGINT(20) NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC) VISIBLE,
  INDEX `fk_category_category1_idx` (`parent_category` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`parent_category`)
    REFERENCES `OnlineStore`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`user` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`user` (
  `user_id` BIGINT(20) NOT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `password_hash` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`adress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`adress` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`adress` (
  `adress_id` BIGINT(20) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `zip_code` VARCHAR(45) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`adress_id`),
  INDEX `fk_adress_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_adress_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `OnlineStore`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`shipping_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`shipping_status` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`shipping_status` (
  `shipping_status_id` BIGINT(20) NOT NULL,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`shipping_status_id`),
  UNIQUE INDEX `status_name_UNIQUE` (`status_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`shipping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`shipping` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`shipping` (
  `shipping_id` BIGINT(20) NOT NULL,
  `shipping_carrier` VARCHAR(45) NOT NULL,
  `tracking_number` VARCHAR(45) NOT NULL,
  `shipped_at` DATETIME NOT NULL,
  `estimated_delivery` DATE NULL,
  `shipping_status_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`shipping_id`, `shipping_status_id`),
  INDEX `fk_shipping_shipping_status1_idx` (`shipping_status_id` ASC) VISIBLE,
  UNIQUE INDEX `shipping_carrier_UNIQUE` (`shipping_carrier` ASC) VISIBLE,
  UNIQUE INDEX `tracking_number_UNIQUE` (`tracking_number` ASC) VISIBLE,
  CONSTRAINT `fk_shipping_shipping_status1`
    FOREIGN KEY (`shipping_status_id`)
    REFERENCES `OnlineStore`.`shipping_status` (`shipping_status_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`order_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`order_status` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`order_status` (
  `order_status_id` BIGINT(20) NOT NULL,
  `status_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`order_status_id`),
  UNIQUE INDEX `status_name_UNIQUE` (`status_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`order` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`order` (
  `order_id` BIGINT(20) NOT NULL,
  `discount` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `order_status_id` BIGINT(20) NOT NULL,
  `shipping_address` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `shipping_id` BIGINT(20) NULL,
  PRIMARY KEY (`order_id`, `order_status_id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_order_adress1_idx` (`shipping_address` ASC) VISIBLE,
  INDEX `fk_order_shipping1_idx` (`shipping_id` ASC) VISIBLE,
  INDEX `fk_order_order_status1_idx` (`order_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `OnlineStore`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_adress1`
    FOREIGN KEY (`shipping_address`)
    REFERENCES `OnlineStore`.`adress` (`adress_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_shipping1`
    FOREIGN KEY (`shipping_id`)
    REFERENCES `OnlineStore`.`shipping` (`shipping_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_order_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `OnlineStore`.`order_status` (`order_status_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`role` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`role` (
  `role_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`product_review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`product_review` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`product_review` (
  `review_id` BIGINT(20) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `rating` DECIMAL(2,1) NULL,
  `created_at` DATETIME NOT NULL,
  `product_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_product_review_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_product_review_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_review_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `OnlineStore`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_review_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `OnlineStore`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`order_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`order_item` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`order_item` (
  `order_id` BIGINT(20) NOT NULL,
  `price_at_order` FLOAT NOT NULL,
  `quantity` SMALLINT(5) NOT NULL,
  `order_id` BIGINT(20) NOT NULL,
  `product_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_item_order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_item_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_item_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `OnlineStore`.`order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_item_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `OnlineStore`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`product_category` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`product_category` (
  `category_id` BIGINT(20) NOT NULL,
  `product_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`category_id`, `product_id`),
  INDEX `fk_product_category_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `OnlineStore`.`category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_category_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `OnlineStore`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`payment_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`payment_method` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`payment_method` (
  `payment_method_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`payment_method_id`),
  UNIQUE INDEX `status_name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`payment` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`payment` (
  `payment_id` BIGINT(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `payment_method_id` BIGINT(20) NOT NULL,
  `order_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`payment_id`, `payment_method_id`),
  INDEX `fk_payment_order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_payment_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_payment_payment_method1_idx` (`payment_method_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `OnlineStore`.`order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `OnlineStore`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_payment_method1`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `OnlineStore`.`payment_method` (`payment_method_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineStore`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineStore`.`user_role` ;

CREATE TABLE IF NOT EXISTS `OnlineStore`.`user_role` (
  `user_user_id` BIGINT(20) NOT NULL,
  `role_role_id` BIGINT(20) NOT NULL,
  INDEX `fk_user_role_user1_idx` (`user_user_id` ASC) VISIBLE,
  INDEX `fk_user_role_role1_idx` (`role_role_id` ASC) VISIBLE,
  PRIMARY KEY (`user_user_id`, `role_role_id`),
  CONSTRAINT `fk_user_role_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `OnlineStore`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_role_id`)
    REFERENCES `OnlineStore`.`role` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
